export default {
  CREATE_DECK_PENDING: "CREATE_DECK_PENDING",
  CREATE_DECK_SUCCESS: "CREATE_DECK_SUCCESS",
  CREATE_DECK_FAIL: "CREATE_DECK_FAIL",

  DRAW_DECK_PENDING: "DRAW_DECK_PENDING",
  DRAW_DECK_SUCCESS: "DRAW_DECK_SUCCESS",
  DRAW_DECK_FAIL: "DRAW_DECK_FAIL",

  ADD_PILE_PENDING: "ADD_PILE_PENDING",
  ADD_PILE_SUCCESS: "ADD_PILE_SUCCESS",
  ADD_PILE_FAIL: "ADD_PILE_FAIL",

  GET_PILE_PENDING: "GET_PILE_PENDING",
  GET_PILE_SUCCESS: "GET_PILE_SUCCESS",
  GET_PILE_FAIL: "GET_PILE_FAIL",
};
