export default {
  CREATE_DECK_PENDING: "CREATE_DECK_PENDING",
  CREATE_DECK_SUCCESS: "CREATE_DECK_SUCCESS",
  CREATE_DECK_FAIL: "CREATE_DECK_FAIL",
  ADD_PILE_PENDING: "ADD_PILE_PENDING",
  ADD_PILE_SUCCESS: "ADD_PILE_SUCCESS",
  ADD_PILE_FAIL: "ADD_PILE_FAIL"
};
